/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IADTHero, IADTHeroInterface } from "../IADTHero";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "enum IADTHero.Military",
            name: "military",
            type: "uint8",
          },
          {
            internalType: "enum IADTHero.Sex",
            name: "sex",
            type: "uint8",
          },
          {
            internalType: "enum IADTHero.Army",
            name: "army",
            type: "uint8",
          },
          {
            internalType: "enum IADTHero.Level",
            name: "level",
            type: "uint8",
          },
        ],
        internalType: "struct IADTHero.HeroInfo",
        name: "hero",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expire",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "buy",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IADTHero__factory {
  static readonly abi = _abi;
  static createInterface(): IADTHeroInterface {
    return new utils.Interface(_abi) as IADTHeroInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IADTHero {
    return new Contract(address, _abi, signerOrProvider) as IADTHero;
  }
}
