/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMarketServicePartnerV1,
  IMarketServicePartnerV1Interface,
} from "../IMarketServicePartnerV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "nft",
        type: "address",
      },
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
    ],
    name: "getProfit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nft",
        type: "address",
      },
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
    ],
    name: "withdrawProfit",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMarketServicePartnerV1__factory {
  static readonly abi = _abi;
  static createInterface(): IMarketServicePartnerV1Interface {
    return new utils.Interface(_abi) as IMarketServicePartnerV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMarketServicePartnerV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMarketServicePartnerV1;
  }
}
