/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface BoxShopInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "OPERATION_ROLE()": FunctionFragment;
    "OWNER_ROLE()": FunctionFragment;
    "_box()": FunctionFragment;
    "addPackage(uint256,uint256,uint256,uint256,address,uint256[],uint256[],string)": FunctionFragment;
    "buy(uint256,uint256)": FunctionFragment;
    "forceReturnERC20(address,uint256,address)": FunctionFragment;
    "forceReturnERC721(address,address,uint256)": FunctionFragment;
    "forceReturnNative(uint256,address)": FunctionFragment;
    "getPackages(uint256,uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "name()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setBox(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "toggleBoxType(uint256)": FunctionFragment;
    "updatePackage(uint256,uint256,uint256,uint256,uint256,address,uint256[],uint256[],string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATION_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_box", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addPackage",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish[],
      BigNumberish[],
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceReturnERC20",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "forceReturnERC721",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceReturnNative",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPackages",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "setBox", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleBoxType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePackage",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish[],
      BigNumberish[],
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATION_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OWNER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_box", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addPackage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forceReturnERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceReturnERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceReturnNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPackages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBox", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleBoxType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePackage",
    data: BytesLike
  ): Result;

  events: {
    "LogAddPackage(tuple)": EventFragment;
    "LogBuy(address,uint256,uint256,uint256)": EventFragment;
    "LogUpdatePackage(tuple)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogAddPackage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogBuy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogUpdatePackage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export class BoxShop extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BoxShopInterface;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    OPERATION_ROLE(overrides?: CallOverrides): Promise<[string]>;

    OWNER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    _box(overrides?: CallOverrides): Promise<[string]>;

    addPackage(
      startTime: BigNumberish,
      endTime: BigNumberish,
      sellLimit: BigNumberish,
      price: BigNumberish,
      currency: string,
      boxTypes: BigNumberish[],
      boxAmounts: BigNumberish[],
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    buy(
      packageId: BigNumberish,
      quantity: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    forceReturnERC20(
      token: string,
      amount: BigNumberish,
      sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    forceReturnERC721(
      sendTo: string,
      token: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    forceReturnNative(
      amount: BigNumberish,
      sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPackages(
      fromIdx: BigNumberish,
      toIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          string,
          BigNumber[],
          BigNumber[],
          string
        ] & {
          isActive: boolean;
          packageId: BigNumber;
          startTime: BigNumber;
          endTime: BigNumber;
          sellLimit: BigNumber;
          sold: BigNumber;
          price: BigNumber;
          currency: string;
          boxTypes: BigNumber[];
          boxAmounts: BigNumber[];
          name: string;
        })[]
      ] & {
        packages: ([
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          string,
          BigNumber[],
          BigNumber[],
          string
        ] & {
          isActive: boolean;
          packageId: BigNumber;
          startTime: BigNumber;
          endTime: BigNumber;
          sellLimit: BigNumber;
          sold: BigNumber;
          price: BigNumber;
          currency: string;
          boxTypes: BigNumber[];
          boxAmounts: BigNumber[];
          name: string;
        })[];
      }
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBox(
      box: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    toggleBoxType(
      packageId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updatePackage(
      packageId: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      sellLimit: BigNumberish,
      price: BigNumberish,
      currency: string,
      boxTypes: BigNumberish[],
      boxAmounts: BigNumberish[],
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  OPERATION_ROLE(overrides?: CallOverrides): Promise<string>;

  OWNER_ROLE(overrides?: CallOverrides): Promise<string>;

  _box(overrides?: CallOverrides): Promise<string>;

  addPackage(
    startTime: BigNumberish,
    endTime: BigNumberish,
    sellLimit: BigNumberish,
    price: BigNumberish,
    currency: string,
    boxTypes: BigNumberish[],
    boxAmounts: BigNumberish[],
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  buy(
    packageId: BigNumberish,
    quantity: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  forceReturnERC20(
    token: string,
    amount: BigNumberish,
    sendTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  forceReturnERC721(
    sendTo: string,
    token: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  forceReturnNative(
    amount: BigNumberish,
    sendTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPackages(
    fromIdx: BigNumberish,
    toIdx: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber[],
      BigNumber[],
      string
    ] & {
      isActive: boolean;
      packageId: BigNumber;
      startTime: BigNumber;
      endTime: BigNumber;
      sellLimit: BigNumber;
      sold: BigNumber;
      price: BigNumber;
      currency: string;
      boxTypes: BigNumber[];
      boxAmounts: BigNumber[];
      name: string;
    })[]
  >;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  name(overrides?: CallOverrides): Promise<string>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBox(
    box: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  toggleBoxType(
    packageId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updatePackage(
    packageId: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    sellLimit: BigNumberish,
    price: BigNumberish,
    currency: string,
    boxTypes: BigNumberish[],
    boxAmounts: BigNumberish[],
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    OPERATION_ROLE(overrides?: CallOverrides): Promise<string>;

    OWNER_ROLE(overrides?: CallOverrides): Promise<string>;

    _box(overrides?: CallOverrides): Promise<string>;

    addPackage(
      startTime: BigNumberish,
      endTime: BigNumberish,
      sellLimit: BigNumberish,
      price: BigNumberish,
      currency: string,
      boxTypes: BigNumberish[],
      boxAmounts: BigNumberish[],
      _name: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buy(
      packageId: BigNumberish,
      quantity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    forceReturnERC20(
      token: string,
      amount: BigNumberish,
      sendTo: string,
      overrides?: CallOverrides
    ): Promise<void>;

    forceReturnERC721(
      sendTo: string,
      token: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    forceReturnNative(
      amount: BigNumberish,
      sendTo: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getPackages(
      fromIdx: BigNumberish,
      toIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber[],
        BigNumber[],
        string
      ] & {
        isActive: boolean;
        packageId: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        sellLimit: BigNumber;
        sold: BigNumber;
        price: BigNumber;
        currency: string;
        boxTypes: BigNumber[];
        boxAmounts: BigNumber[];
        name: string;
      })[]
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setBox(box: string, overrides?: CallOverrides): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    toggleBoxType(
      packageId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePackage(
      packageId: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      sellLimit: BigNumberish,
      price: BigNumberish,
      currency: string,
      boxTypes: BigNumberish[],
      boxAmounts: BigNumberish[],
      _name: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    LogAddPackage(
      package?: null
    ): TypedEventFilter<
      [
        [
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          string,
          BigNumber[],
          BigNumber[],
          string
        ] & {
          isActive: boolean;
          packageId: BigNumber;
          startTime: BigNumber;
          endTime: BigNumber;
          sellLimit: BigNumber;
          sold: BigNumber;
          price: BigNumber;
          currency: string;
          boxTypes: BigNumber[];
          boxAmounts: BigNumber[];
          name: string;
        }
      ],
      {
        package: [
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          string,
          BigNumber[],
          BigNumber[],
          string
        ] & {
          isActive: boolean;
          packageId: BigNumber;
          startTime: BigNumber;
          endTime: BigNumber;
          sellLimit: BigNumber;
          sold: BigNumber;
          price: BigNumber;
          currency: string;
          boxTypes: BigNumber[];
          boxAmounts: BigNumber[];
          name: string;
        };
      }
    >;

    LogBuy(
      user?: null,
      packageId?: null,
      quantity?: null,
      totalPrice?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        user: string;
        packageId: BigNumber;
        quantity: BigNumber;
        totalPrice: BigNumber;
      }
    >;

    LogUpdatePackage(
      package?: null
    ): TypedEventFilter<
      [
        [
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          string,
          BigNumber[],
          BigNumber[],
          string
        ] & {
          isActive: boolean;
          packageId: BigNumber;
          startTime: BigNumber;
          endTime: BigNumber;
          sellLimit: BigNumber;
          sold: BigNumber;
          price: BigNumber;
          currency: string;
          boxTypes: BigNumber[];
          boxAmounts: BigNumber[];
          name: string;
        }
      ],
      {
        package: [
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          string,
          BigNumber[],
          BigNumber[],
          string
        ] & {
          isActive: boolean;
          packageId: BigNumber;
          startTime: BigNumber;
          endTime: BigNumber;
          sellLimit: BigNumber;
          sold: BigNumber;
          price: BigNumber;
          currency: string;
          boxTypes: BigNumber[];
          boxAmounts: BigNumber[];
          name: string;
        };
      }
    >;

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    OPERATION_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    OWNER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    _box(overrides?: CallOverrides): Promise<BigNumber>;

    addPackage(
      startTime: BigNumberish,
      endTime: BigNumberish,
      sellLimit: BigNumberish,
      price: BigNumberish,
      currency: string,
      boxTypes: BigNumberish[],
      boxAmounts: BigNumberish[],
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    buy(
      packageId: BigNumberish,
      quantity: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    forceReturnERC20(
      token: string,
      amount: BigNumberish,
      sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    forceReturnERC721(
      sendTo: string,
      token: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    forceReturnNative(
      amount: BigNumberish,
      sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPackages(
      fromIdx: BigNumberish,
      toIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBox(
      box: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    toggleBoxType(
      packageId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updatePackage(
      packageId: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      sellLimit: BigNumberish,
      price: BigNumberish,
      currency: string,
      boxTypes: BigNumberish[],
      boxAmounts: BigNumberish[],
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OPERATION_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    OWNER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _box(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addPackage(
      startTime: BigNumberish,
      endTime: BigNumberish,
      sellLimit: BigNumberish,
      price: BigNumberish,
      currency: string,
      boxTypes: BigNumberish[],
      boxAmounts: BigNumberish[],
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    buy(
      packageId: BigNumberish,
      quantity: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    forceReturnERC20(
      token: string,
      amount: BigNumberish,
      sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    forceReturnERC721(
      sendTo: string,
      token: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    forceReturnNative(
      amount: BigNumberish,
      sendTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPackages(
      fromIdx: BigNumberish,
      toIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBox(
      box: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toggleBoxType(
      packageId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updatePackage(
      packageId: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      sellLimit: BigNumberish,
      price: BigNumberish,
      currency: string,
      boxTypes: BigNumberish[],
      boxAmounts: BigNumberish[],
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
