/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface RevertInterface extends ethers.utils.Interface {
  functions: {
    "hit()": FunctionFragment;
    "hit2()": FunctionFragment;
    "hit3()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "hit", values?: undefined): string;
  encodeFunctionData(functionFragment: "hit2", values?: undefined): string;
  encodeFunctionData(functionFragment: "hit3", values?: undefined): string;

  decodeFunctionResult(functionFragment: "hit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hit2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hit3", data: BytesLike): Result;

  events: {};
}

export class Revert extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RevertInterface;

  functions: {
    hit(overrides?: CallOverrides): Promise<[BigNumber]>;

    hit2(overrides?: CallOverrides): Promise<[BigNumber]>;

    hit3(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  hit(overrides?: CallOverrides): Promise<BigNumber>;

  hit2(overrides?: CallOverrides): Promise<BigNumber>;

  hit3(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    hit(overrides?: CallOverrides): Promise<BigNumber>;

    hit2(overrides?: CallOverrides): Promise<BigNumber>;

    hit3(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    hit(overrides?: CallOverrides): Promise<BigNumber>;

    hit2(overrides?: CallOverrides): Promise<BigNumber>;

    hit3(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    hit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hit2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hit3(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
